spring:
  jpa:
    database: POSTGRESQL
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: update
    properties:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/springproject
    username: postgres
    password: 2901
    driver-class-name: org.postgresql.Driver
    server:
      port=8001:

server:
  port: 9999